spring:
  jpa:
    database: postgresql
  application:
    name: king_credits
  datasource:
    name: king_credits
    url: jdbc:postgresql://localhost:5432/king_credits
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/king_credits
    user: postgres
    schemas: public
bot:
  name: DreamDropCriticalOps_bot
  token: 7635813026:AAHnoE2MIWXQzGBBzfRRTpTMRkET1COQ-uo
telegram:
  channel:
    username: ${USERNAME:@CriticalOpsLeaks}
    url-telegram-channel: ${URL:https://t.me/CriticalOpsLeaks}
    url: ${URL:https://t.me/CriticalOpsLeaks}
