CREATE TABLE IF NOT EXISTS cases_item
(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR,
    price DOUBLE PRECISION,
    coefficient DOUBLE PRECISION,
    photo_data BYTEA,
    cases_name VARCHAR
)